### ISSUE TITLE
<input type="file"/> breaks iPhoneX

### ISSUE THREAD

**Issue by landabaso** [apache/cordova-plugin-statusbar#127] opened 2019-02-01 12:26 UTC
Place an `<input type="file"/>` TAG somewhere in your App.

Click on it, then click on "Browse", so that iOS displays the System Browser.
Then you can click on "Cancel" and Boom, when you are back to your App the safe area space for the Virtual HomeBar has disappeared.

I'm using `<plugin name="cordova-plugin-splashscreen" spec="^5.0.2" />` (using image sizes for iPhoneX), also using `<plugin name="cordova-plugin-statusbar" spec="2.4.2" />`.

The combination works perfectly in all circumstances except when calling the System Dialogs (Browse / Photo Library).

**Comment by janpio** [comment] 2019-06-19 14:37
What is "the safe area space for the Virtual HomeBar"?

**Comment by jcesarmobile** [comment] 2019-10-19 15:12
Closing as is unclear what the problem is and has not answered after a reasonable amount of time.
Feel free to report it again providing more details

**Closed by jcesarmobile** 2019-10-19 15:12 UTC
Labels: support
