### ISSUE TITLE
Status bar background color overridden on Android 13

### ISSUE THREAD

**Issue by gmilof** [apache/cordova-plugin-statusbar#244] opened 2022-09-27 08:13 UTC
# Bug Report

## Problem
On Android 13 the status bar background color is always black. I've set the color on the config.xml with the StatusBarBackgroundColor preference and it works on ios and android < 13 but not on Android 13.
### What is expected to happen?
Status bar should have the color I've set.

### What does actually happen?
Status bar color is black. It shows my color for a few milliseconds than it becomes black.

## Information

Just set the background color with StatusBarBackgroundColor in the config.xml and run the application on Android 13.

### Command or Code

`<preference name="StatusBarBackgroundColor" value="#cccccc" /> in config.xml
`

### Environment, Platform, Device

Android 13, Android studio 2021.2.1 patch 2

### Version information

cordova cli v 11.0.0
cordova-android v 11.0.0
cordova-plugin-statusbar v3.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by gmilof** [comment] 2022-09-27 13:25
It seems like this is caused by the animation in the splash screen plugin.
Commenting this out in the splash screen plugin:
![image](https://user-images.githubusercontent.com/103517918/192538652-e0654498-5d1e-4fb4-9da6-8bcc08c023f7.png)
solves this issue.

**Comment by jcesarmobile** [comment] 2022-10-10 23:01
closing as duplicate of https://github.com/apache/cordova-android/issues/1501 since the problem is on cordova-android and not in the plugin

**Closed by jcesarmobile** 2022-10-10 23:01 UTC
