### ISSUE TITLE
Playing video on iOS and shifting from landscape to portrait messes up status bar

### ISSUE THREAD

**Issue by sithwarrior** [apache/cordova-plugin-statusbar#268] opened 2023-10-20 08:45 UTC
# Bug Report
Playing video on iOS and shifting from landscape to portrait messes up status bar

same as #221 
### What is expected to happen?
Statusbar stays in place

### What does actually happen?
Content slides up under status bar

## Information
Watching a video in an iOS Webview, defaults to fullscreen, if you rotate your phone to landscape, then back to portrait and exit the video, the status bar is then off

our settings is

`<preference name="StatusBarOverlaysWebView" value="false" />`

And we only allow portrait orientation, but watching videos is done in a native iOS player by default, which allows rotating.

As the backbutton now is "behind" the status bar, my workaround has been setting the eventlistener on `statusTap` and then doing 

```
window.StatusBar.overlaysWebView(true);
window.StatusBar.overlaysWebView(false);
```

I don't know exactly what causing this, but it seems like the resetup of the statusbar isn't called in this situation.

### Command or Code
see above

### Environment, Platform, Device
iOS
`<preference name="StatusBarOverlaysWebView" value="false" />`
only allow portrait orientation

### Version information
Newest Cordova, Cordova IOS, Cordova ionic WKWebview and newest Statusbar Plugin

## Checklist

- [ X] I searched for existing GitHub issues
- [ X] I updated all Cordova tooling to most recent version
- [ X] I included all the necessary information above

**Comment by Heshyo** [comment] 2024-01-23 14:35
I guess I have the same issue. My app is also portrait only, except when playing a video where the player allows both portrait and landscape.

If I open a video in portrait, and stays in portrait, then no problem.

If I open a video in portrait, go to landscape, then close the video, then no problem.

The issue arises when opening the video in portrait, going to landscape, then portrait again, then closing the video. The app is now on top of the status bar, and simply calling `window.StatusBar.overlaysWebView(false);` does not help. As @sithwarrior mentioned, you have to change the overlay to `true` then `false`:

```
window.StatusBar.overlaysWebView(true);
window.StatusBar.overlaysWebView(false);
```

I call this in the `webkitendfullscreen` event.

**Comment by Heshyo** [comment] 2024-01-24 02:24
Another way to make the problem appear:

open a video in portrait, then close the player by swiping it down.

The app is now on top of the status bar. The issue with this one is that the `webkitendfullscreen` event is never called and I don't notice that I must call `overlaysWebView`.

**Comment by jcesarmobile** [comment] 2024-01-28 11:15
can you provide a sample app that reproduces the issue?

**Comment by Heshyo** [comment] 2024-01-28 14:05
@jcesarmobile @sithwarrior I'm away from a Mac for some time, but it'll try to provide a sample app in a week or two.

**Comment by jcesarmobile** [comment] 2024-06-29 11:30
closing since no sample app was provided

**Closed by jcesarmobile** 2024-06-29 11:30 UTC
Labels: info-needed
