### ISSUE TITLE
Style change not working on iPhone 11

### ISSUE THREAD

**Issue by derweise** [apache/cordova-plugin-statusbar#188] opened 2020-05-26 07:05 UTC
## Problem

`StatusBar.styleDefault() `

does not change text color to black on real iPhone 11 device. In iPhone 11 emulator working correctly though.

### What is expected to happen?

Font color of statusbar should change to dark color

### What does actually happen?

It does not change

### Version information
```
U2007750s-MBP:Source u2007750$ ionic info

Ionic:

   Ionic CLI          : 5.4.16
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 8 other plugins)

Utility:

   cordova-res (update available: 0.14.0) : 0.8.0
   native-run (update available: 1.0.0)   : 0.2.7

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v10.15.3 (/Users/u2007750/.nvm/versions/node/v10.15.3/bin/node)
   npm        : 6.4.1
   OS         : macOS Catalina
   Xcode      : Xcode 11.4 Build version 11E146
```

**Comment by jcesarmobile** [comment] 2020-06-05 09:27
Duplicate of https://github.com/apache/cordova-plugin-statusbar/issues/148

**Closed by jcesarmobile** 2020-06-05 09:27 UTC
