### ISSUE TITLE
iOS 13 Webview Shifted after Camera Closed

### ISSUE THREAD

**Issue by m-s-morgan** [apache/cordova-plugin-statusbar#156] opened 2019-09-24 23:32 UTC
# Bug Report

## Problem

When either the camera or the image picker is pulled up and then closed either by canceling or performing the intended action, the entire webview is shifted up so that it appears as if the status bar is overlaying the webview (app content is behind the status bar). 

### What is expected to happen?

The webview should appear as it did when the camera or image picker was initially launched.

### What does actually happen?

Upon close, the webview is behind the status bar.

## Information

This only appears to happen in iOS 13 with the cordova-plugin-camera. I am using the cordova-plugin-wkwebview, but no other plugins seem to shift the webview so I'm assuming it's either an issue with this plugin or how something this plugin is doing reacts with the wkwebview.

### Command or Code

Launch the camera or image picker, then close it.

### Environment, Platform, Device

IPhone X with iOS 13.1.

### Version information
Cordova 9.0.0
cordova-plugin-camera 4.1.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by AlexanderStasyuk** [comment] 2019-10-10 21:00
Have similar issue with our app. It happens via getting to use camera two different ways:

1.  When using cordova-plugin-camera to capture photo or photo picker the issue happens.
2.  Also, if using the input type="file" way to use the webview/safari api to access camera or photo picker.

The way #1 is resolved by using the solution purposed by @Crash-- 
But way #2 still persists. 
In the way #2 we are not using cordova-plugin-camera but using the native web browser/view api.
Thus probably solution needs to be implemented in the cordova-plugin-statusbar or some other clever css way that has been suggested by @markerio

**Comment by iamrafo** [comment] 2019-10-15 14:25
statusBar.hide();
statusBar.show();
:))) not a good way but fixed

**Closed** 2019-10-20 10:16 UTC

**Comment by lentyaishe** [comment] 2019-11-13 11:15
> statusBar.hide();
> statusBar.show();
> :))) not a good way but fixed

My solution was exactly the same and it does the job. Put it in both success and error calls of your camera.getPicture().

**Comment by tryhardest** [comment] 2020-01-28 19:09
@jcesarmobile actually the comment you posted "moving to cordova-plugin-statusbar, that's the plugin doing the resizing and causing the issue" might be incorrect? Due to the fact that yes, it IS the statusBar causing this, but even without the statusBar plugin we experience this on Android. When we programatically remove statusBar it does not occur. But even without plugin, it does.

**Comment by jcesarmobile** [comment] 2020-01-28 19:11
well, the issue is for iOS and it was fixed in the statusbar plugin already, so I'm not wrong, you are just facing a different issue.

**Comment by tryhardest** [comment] 2020-01-28 19:14
@jcesarmobile yes I guess both are true. Have you any suggestions for handing a status bar webview jump on Android (with or without the statusBar plugin)?

**Comment by dolin-tan** [comment] 2020-03-24 08:50
in iOS   When we use the camera plugin to take pictures or select pictures, the plugin will automatically make "StatusBarOverlaysWebView" true , So it will cause the page to move up，I have installed the latest version of the camera plugin, but there is still a problem
@jcesarmobile

**Comment by singhc00** [comment] 2020-04-29 08:58
> Have similar issue with our app. It happens via getting to use camera two different ways:
> 
> 1. When using cordova-plugin-camera to capture photo or photo picker the issue happens.
> 2. Also, if using the input type="file" way to use the webview/safari api to access camera or photo picker.
> 
> The way #1 is resolved by using the solution purposed by @Crash--
> But way #2 still persists.
> In the way #2 we are not using cordova-plugin-camera but using the native web browser/view api.
> Thus probably solution needs to be implemented in the cordova-plugin-statusbar or some other clever css way that has been suggested by @markerio

Hi

Did you end up finding a solution for the issue where it shifts the app behind the Status bar when using the camera from the <input> i.e. Safari Webview input file element.
