### ISSUE TITLE
iPhone XS when app is changed from portrait view to landscape view and then back to portrait view the status menu appears on top of the application menu

### ISSUE THREAD

**Issue by chugh97** [apache/cordova-plugin-statusbar#152] opened 2019-09-06 15:16 UTC
# Bug Report

## Problem
![img5](https://user-images.githubusercontent.com/1386130/64438856-ba55e380-d0c0-11e9-863b-739eceb873f1.png)

### What is expected to happen?

The menu bar appears below the status

### What does actually happen?

menu and status bars are one top of each other. User cannot use the menu once phone has been changed from Portrait to Landscape and then back to Portrait

### Environment, Platform, Device

Apcahe cordova
Ionic

### Version information

- [X ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ X] I included all the necessary information above

**Comment by jcesarmobile** [comment] 2019-09-19 18:07
Those menus are yours, right? I don't think the problem is in the plugin but in your app.
Would be good if you could provide a sample app

**Comment by yqGitHub** [comment] 2019-10-23 03:16
I have the same question: before landscape is ok, but  changed from  landscape view to portrait view on ios 13

**Comment by jcesarmobile** [comment] 2022-06-01 23:10
Closing as the reporter didn’t answer

**Closed by jcesarmobile** 2022-06-01 23:10 UTC
Labels: info-needed
