### ISSUE TITLE
styleDefault not working on IOS in dark mode

### ISSUE THREAD

**Issue by HusFNS** [apache/cordova-plugin-statusbar#204] opened 2020-10-16 14:57 UTC
# Bug Report

### What is expected to happen?
I expected dark text on a white background

### What does actually happen?
white text on a white background

## Information

Only happening on iphone in darkmode

### Command or Code

this.statusBar.show();
this.statusBar.overlaysWebView(false);
this.statusBar.styleDefault();
this.statusBar.backgroundColorByHexString('#FFFFFF');

### Environment, Platform, Device

IOS in Dark mode

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by TheTonnio** [comment] 2020-10-27 14:53
I think that solutions for this issue are valid for your problem:
https://github.com/apache/cordova-plugin-statusbar/issues/148

**Comment by doginthehat** [comment] 2020-11-19 12:04
I'm getting the same issue as @HusFNS and can't get it to display correctly.

I've tried all the options from #148 but it doesn't help.

There is actually a fix in current master that resolves the problem https://github.com/apache/cordova-plugin-statusbar/blob/29283396113ab1c46d36b61f397f5cdde32686f7/src/ios/CDVStatusBar.m#L303 but it's not published into a release yet.

Not sure if anyone from repo is watching this issue but it would be great if it could be published.

Additionally, the following function should be made accessible:

```
- (void) styleDarkContent:(CDVInvokedUrlCommand*)command
{
    [self setStyleForStatusBar:3];
}
```

(and the matching in plugin js file)

```
styleDarkContent: function () {
		exec(null, null, "StatusBar", "styleDarkContent", []);
	},
```

Hope this help

**Comment by ChristopherGeel** [comment] 2020-12-14 10:52
Hi guys, 

Does anyone have a working solution to this yet? None of the solutions in #148 worked for me. 

I see that @doginthehat mentioned that there is fix but that it has not yet been published. Any news on this?

**Comment by HusFNS** [comment] 2020-12-14 11:14
@ChristopherGeel  I am going to test in de upcomming days.

**Comment by echonox** [comment] 2020-12-15 17:54
@ChristopherGeel @HusFNS tested latest master branch, the fix works ok

**Comment by ChristopherGeel** [comment] 2020-12-17 06:42
@echonox thanks, that is great news. Do you know when it will be published?

**Comment by echonox** [comment] 2020-12-19 15:24
@ChristopherGeel not sure, but I'm using master just fine

**Comment by timbru31** [comment] 2021-01-08 15:29
Closing as a duplicate of #148 - the master is confirmed to fix the issue. You can use it with `cordova plugin add https://github.com/apache/cordova-plugin-statusbar.git#master`

**Closed by timbru31** 2021-01-08 15:29 UTC
