### ISSUE TITLE
Plugin not working on Android 9

### ISSUE THREAD

**Issue by diamond95** [apache/cordova-plugin-statusbar#155] opened 2019-09-25 16:48 UTC
I'm trying to fix issue with StatusBarOverlaysWebView, but it's not working on Android 9. 

How it looks like on Android 9: https://ibb.co/BZ4KVpB

How it looks like on PhoneGap Developer Application: https://ibb.co/W5574HC

I tried every possible combination editing config.xml. Now my config.xml look like this: 
```xml
<platform name="android">
    <preference name="StatusBarStyle" value="lightcontent" />
    <preference name="android-minSdkVersion" value="21" />
    <allow-intent href="market:*" />
    <preference name="StatusBarBackgroundColor" value="#000000" />
    <preference name="StatusBarDefaultScrollToTop" value="false" />
    <preference name="StatusBarOverlaysWebView" value="true" />
</platform>
```

I run plugin with JS and it gives me normally object of StatusBar:
```javascript
  document.addEventListener('deviceready', fullScreen);
  function fullScreen() {
    AndroidFullScreen.setSystemUiVisibility(AndroidFullScreen.SYSTEM_UI_FLAG_FULLSCREEN | AndroidFullScreen.SYSTEM_UI_FLAG_LOW_PROFILE);
    console.log(StatusBar);
    if (cordova.platformId == 'android') {
      StatusBar.overlaysWebView(true);
      StatusBar.backgroundColorByHexString('#33000000');
       
    } 
  }
```

Is there any trick about this?

**Comment by breautek** [comment] 2019-09-25 17:02
Setting `backgroundColorByHexString` and `overlaysWebView(true)` are two conflicting states and I'm pretty sure they'll override each other.

If you want the status bar overlayed, then I would just use `overlaysWebView(true)`.

Also, using `overlaysWebView` will set/unset UI flags so `AndroidFullScreen.setSystemUiVisibility(AndroidFullScreen.SYSTEM_UI_FLAG_FULLSCREEN | AndroidFullScreen.SYSTEM_UI_FLAG_LOW_PROFILE);` may be conflicting, but I'm not sure.

Note that right now, you must use the JS api `StatusBar.overlaysWebView(true);` as you are using right now. The overlay preference is broken, pending PR https://github.com/apache/cordova-plugin-statusbar/pull/142 for a fix.

**Comment by diamond95** [comment] 2019-09-26 10:09
I tried without setting backgroudColorByHexString and its not working. 
Also, I comment out AndroidFullScreen.., same problem. 

So, we wait for fix or ? 
Thanks for quick response

**Comment by breautek** [comment] 2019-10-01 20:28
Below should be all you need to set the statusbar to overlay mode. It will make the status bar transparent, and your webview will appear **underneath** the status bar (so `padding-top` may be necessary).

```javascript
document.addEventListener('deviceready', () => {
    StatusBar.overlaysWebView(true);
});
```

**Comment by diamond95** [comment] 2019-10-01 22:34
padding-top did not resolve my issue. 
I have created simple blank application with:
` StatusBar.overlaysWebView(true);  
    StatusBar.backgroundColorByName("red");`
, where on Android 9 statusbar is >black< and on PhoneGap dev application Statusbar is >Red<.
...
After some testing: I tried to `alert(Statusbar);`

1. https://ibb.co/ssFfRW6

After clicking OK:

2. https://ibb.co/3MgWxrj

Something wierd is happening

**Comment by breautek** [comment] 2019-10-01 22:50
Please provide a reproduction app, then I can take a look at it.

https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by breautek** [comment] 2019-10-02 01:03
Playing around with your app, I did find some weird behaviour...

If `StatusBar.overlaysWebView(true);` is called on `deviceready` event, then the statusbar does **not** go into overlay mode as expected. Trying to call it again through the console and the API call appears to do nothing. Setting it to `false` then `true` again via the console appears to correct the problem.

Additionally, if I omit the `StatusBar.overlaysWebView(true);` call on `deviceready` altogether. Then invoke `StatusBar.overlaysWebView(true);` via the console, it works the first time, 100% of the time.

Lastly if I do:

```javascript
setTimeout(() => {
      StatusBar.overlaysWebView(true);
    }, 1000);
```

in the `deviceready` event, consistently the statusbar goes into overlay mode (after a second delay obviously).

This tells me there is some kind of asynchronous or race condition problem with the plugin.

**Comment by breautek** [comment] 2019-10-02 01:21
I'd say there are actually two problems.

First is the one I described above. The second is `overlaysWebView(true)` will clear the set background colour. I don't think this is necessary. Toggling the webview overlay should remember the set background color of the statusbar.

**Comment by breautek** [comment] 2019-10-02 02:02
Because two issues isn't really related I've created two new issues, specifically for issues I found, #158 & #159. That way both issues can be tracked or worked on independently. You're welcome subscribe to the new issues.

In the meantime, there are two workarounds that I can foresee:

The first one as I already stated it, wrap the `StatusBar` APIs in a `setTimeout`. This is obviously very dirty and might not be reliable however, and definitely doesn't make your app look very professional.

So I'd suggest another workaround:

I would fork this statusbar plugin, and apply the https://github.com/apache/cordova-plugin-statusbar/pull/142 PR to your fork. This will fix the `StatusBarOverlaysWebView` preference inside `config.xml` and allow you to set these modes without relying on the JS APIs. This should work as when I was experimenting with your app, I copied the statusbar state to plugin native initialization to see if the behaviour changed and when doing so, your app's statusbar was working as expected.

Let me know if any of these workarounds work for you

**Comment by diamond95** [comment] 2019-10-02 08:38
Thanks for checking out my problem! 
I tried your following example with setTimeout function, and still it's same problem, not working. 
When I open application on android, it automatically shows me black statusbar ( which is ok ), and after timeout for few seconds nothing have changed. 
Did you change something in config.xml, which, maybe working for you? 

I would like to use that solution while plugin will be fixed. 

Regards

**Comment by breautek** [comment] 2019-10-02 13:36
I did change some stuff in your repo during my experimentation. I pushed my changes in a new branch on your repo.

**Comment by diamond95** [comment] 2019-10-02 23:03
@breautek thanks, but simply now I'm trying to make that status bar transparent without any color.. 
I tried your update, and there is still black statusbar. 

> If this value is not set, the background color will be transparent.
I did not set any background color. Check updated repo please.. and thank you, really!

**Comment by Akronae** [comment] 2020-01-05 17:41
Okay I've found that using this structure works

```js
StatusBar.overlaysWebView(false);
setTimeout(()=>
{
    StatusBar.overlaysWebView(true)
    setTimeout(() =>
    {
        StatusBar.backgroundColorByHexString('#22200000')
   }, 100)
}, 100)
```
Kind of stinky but it's the only way to making it work 😂
I've also noticed that when not using this technique, focusing an input field and having the keyboard getting displayed makes the status bar render as it should.

Hope this helps

**Comment by breautek** [comment] 2020-01-05 18:36
I'm closing this issue in favour of the two issues reported at https://github.com/apache/cordova-plugin-statusbar/issues/158 and https://github.com/apache/cordova-plugin-statusbar/issues/159 to help keep things organized.

@Akronae Using timeouts like in your code snippet is a workaround to https://github.com/apache/cordova-plugin-statusbar/issues/158

**Closed by breautek** 2020-01-05 18:36 UTC
Labels: bug, platform: android

**Comment by marsgpl** [comment] 2023-08-14 19:32
I faced the same problem and I've found the reason and the solution.

Reason:
cordova has default splashscreen plugin, which sets the **post-theme** of the main activity after splash screen hides: https://cordova.apache.org/docs/en/11.x/core/features/splashscreen/#androidpostsplashscreentheme

the default value for that action is @style/Theme.AppCompat.NoActionBar, which provides theme with black statusbar.

since hiding splashscreen takes non-zero time (especially when fade is on with non-zero duration: https://cordova.apache.org/docs/en/11.x/core/features/splashscreen/#fadesplashscreen)

it leads to race condition with this plugin, when we try to do something like

```javascript
document.addEventListener('deviceready', () => {
    navigator.splashscreen?.hide()
    window.StatusBar.backgroundColorByHexString('#ff0000')
}, { once: true })
```

Solution: add custom theme and provide it to AndroidPostSplashScreenTheme setting.

cordova's config.xml:
```xml
<widget ...>
    <platform name="android">
        <preference name="AndroidPostSplashScreenTheme" value="@style/PostSplashScreen" />
    </platform>
</widget>
```

then go to **platforms/android/app/src/main/res/values/themes.xml** and add the new theme:

```xml
<resources>
   ... other styles
    <style name="PostSplashScreen" parent="@style/Theme.AppCompat.Light.NoActionBar">
        <item name="colorPrimary">#ff0000</item>
        <item name="colorPrimaryDark">#ff0000</item>
        <item name="colorAccent">#ff0000</item>
        <item name="android:statusBarColor">#ff0000</item>
    </style>
</resources>
```

https://github.com/apache/cordova-plugin-statusbar/assets/1058743/bc049ada-82fd-4762-87b4-4ebf0c6d9747


And that's it. No timeouts needed.
