### ISSUE TITLE
StatusBar not changing Color on Android 13

### ISSUE THREAD

**Issue by niklas-simon** [apache/cordova-plugin-statusbar#266] opened 2023-09-15 13:58 UTC
# Bug Report

### What is expected to happen?

In the callback of "deviceready" when executing backgroundColorByHexString, StatusBar should change color.

### What does actually happen?

StatusBar doesn't change color.

## Information

This only happens on Android 13. On Android 12 and lower, everything works as expected.  
I debugged the issue using Android Studio and saw that the relevant functions get executed without error. Note that when setting a break point, everything works. Without a break point however, it doesn't.  
I also found out that setting a timeout of about 2 seconds fixes the issue but is not a great solution.

### Command or Code

```
function applyTheme() {
    window.StatusBar.styleLightContent();
    window.StatusBar.backgroundColorByHexString("#2196f3");
}
document.addEventListener("deviceready", function () {
    applyTheme();
});
```
in 'config.xml':
```
<preference name="StatusBarOverlaysWebView" value="false" />
```

### Environment, Platform, Device, Versions

Platform: Android 13
Device: Pixel 7a
Cordova-Android: 12.0.1
Cordova-CLI: 12

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by fpauk** [comment] 2023-10-17 10:28
Thanks for this !    - Did ou also find a way to change the font color

**Comment by niklas-simon** [comment] 2023-10-17 12:44
by using
```
window.StatusBar.styleLightContent();
```
or 
```
window.StatusBar.styleDefault();
```
you should be able to set the font color to black/white respectivly, but as mentioned above, on Android 13, this doesn't work.

**Comment by TiBz0u** [comment] 2023-10-27 16:24
Hi,

_For who is interested by a workaround._

I achieve to add a custom statusBar color by defining a new Theme (on a Samsung running Android 13).

Since Cordova Android 11, Cordova implements `Splashscreen API`. After showing the splashScreen, a new theme is applied to the main activity. 

So first, in config.xml, define the theme you want to load (see [documentation](```
https://cordova.apache.org/docs/en/11.x/core/features/splashscreen/#androidpostsplashscreentheme)) after the splashScreen.
```
<preference name="AndroidPostSplashScreenTheme" value="@style/Theme.Custom"/>
```

After, you need to define the new theme (with cordova hook). Don't forget to define your color or use a existing android color.
```xml
<?xml version="1.0" encoding="utf-8" ?>
<resources>
    <style name="Theme.Custom" parent="@style/Theme.AppCompat.NoActionBar">
        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name="android:statusBarColor">@color/custom</item>
        <item name="android:windowLightStatusBar">false</item>
        <item name="android:windowTranslucentStatus">false</item>
    </style>
</resources>
``` 
Pay attention that
- This method implies to put ` android-minSdkVersion`  to 23
- This method will set the statusBar color for the whole application

Kr.

**Comment by jondspa** [comment] 2023-10-30 21:48
Along the same lines as TiBzOu: I achieved a white background status bar with dark text.  Tested `on` Android 9, 11, 12, and 13.  Hope it helps someone!

* I have these lines in my config file:
 ```
<preference name="StatusBarStyle" value="default" />
<preference name="StatusBarBackgroundColor" value="#FFFFFF" />
```
* I added to the themes.xml file:
```
<item name="android:windowLightStatusBar">
    true
</item>
```

    - Jon

**Comment by jcesarmobile** [comment] 2024-01-28 11:13
can you provide a sample app that reproduces the issue?

**Comment by mohammadrafigh** [comment] 2024-01-28 12:45
@jcesarmobile I'm currently not able to provide a sample app due to lack of enough free time. But I can approve that the reason of this issue is related to the changes on how Splashscreen works as @TiBz0u and @jondspa mentioned above. Splashscreen plugin now starts the main activity of the app with a predefined default theme using `AndroidPostSplashScreenTheme` property. So the clean way to handle that is to add these inside the Android platform of config.xml:
(fine tune with your paths and your needs)

```
<!-- Load our own theme to style navigation bar for API >= 27 -->
<preference name="AndroidPostSplashScreenTheme" value="@style/MyCustomTheme"/>
<!-- Our theme doesn't include anything special for API < 27 -->
<config-file target="res/values/themes.xml" parent="/resources/">
    <style name="MyCustomTheme" parent="Theme.AppCompat.NoActionBar"></style>
</config-file>
<!-- Copy our own theme to style navigation bar for API >= 27 -->
<resource-file src="res/theme/android/values-v27/themes.xml" target="app/src/main/res/values-v27/themes.xml" />
```

then add a `themes.xml` file under the provided path, like this:

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <style name="MyCustomTheme" parent="Theme.AppCompat.NoActionBar">
    <item name="android:statusBarColor">#002860</item>
  </style>
</resources>
```

**Comment by jcesarmobile** [comment] 2024-06-29 11:35
closing since no sample app was provided, but yeah, the problem is the splash screen not allowing changes to the status bar while it's being animated.
Should be solved by setting `FadeSplashScreen` to false, requires cordova-android 12.0.0
see https://github.com/apache/cordova-android/pull/1506

**Closed by jcesarmobile** 2024-06-29 11:35 UTC
Labels: info-needed

**Comment by Venegrad** [comment] 2025-02-17 11:32
Same issue

**Comment by trayvon2017** [comment] 2025-02-24 06:49
> closing since no sample app was provided, but yeah, the problem is the splash screen not allowing changes to the status bar while it's being animated. Should be solved by setting `FadeSplashScreen` to false, requires cordova-android 12.0.0 see [apache/cordova-android#1506](https://github.com/apache/cordova-android/pull/1506)

worked for me on android14

**Comment by BenLaKnet** [comment] 2025-09-23 02:18
It's running for me and it replaces usage of StatusBar plugin:


```
<platform name="android">
	<preference name="AndroidPostSplashScreenTheme" value="@style/Theme.Custom"/>
	<config-file target="res/values/colors.xml" parent="/resources/">
		<color name="StatusBarTheme">#66c5fb</color>
	</config-file>
	<resource-file src="/www/res/StatusBarTheme.xml" target="/app/src/main/res/values/StatusBarTheme.xml" />
</platform>
```

**Comment by mike-nelson** [comment] 2025-10-21 23:24
I found the only way to stop edge-to-edge overriding fullscreen=false was to add all this code in MainActivity onCreate (obviously i could have put it in a better place eg statusbar plugin). 

        // 1) Explicitly stop edge-to-edge: make window fit system windows again (Android 11+)
        WindowCompat.setDecorFitsSystemWindows(getWindow(), true);

        // 2) Clear any lingering fullscreen flags
        getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_FORCE_NOT_FULLSCREEN);

        // 3) Apply system bar insets as padding so content sits below status bar and above nav bar
        final View content = getWindow().getDecorView().findViewById(android.R.id.content);
        if (content != null) {
            ViewCompat.setOnApplyWindowInsetsListener(content, (v, insets) -> {
                Insets sys = insets.getInsets(
                        WindowInsetsCompat.Type.statusBars() |
                                WindowInsetsCompat.Type.navigationBars() |
                                WindowInsetsCompat.Type.displayCutout()
                );
                v.setPadding(0, sys.top, 0, sys.bottom);
                return WindowInsetsCompat.CONSUMED;
            });
            // request an inset pass now
            ViewCompat.requestApplyInsets(content);
        }

**Comment by sdeprada** [comment] 2025-12-03 19:24
In my case, it only began to work when I put these two lines on config.xml:

```
<preference name="FadeSplashScreen" value="false" />
<preference name="StatusBarBackgroundColor" value="#FE969E" />
```

**Comment by GitToTheHub** [comment] 2025-12-03 22:09
Maybe `cordova-android` `15.0.0` will fix this, as the statusbar will be handled by it and not by this plugin anymore, see https://github.com/apache/cordova-android/pull/1817. You can test the latest changes of `cordova-android` with `cordova add platform android@nightly`
