### ISSUE TITLE
[android] StatusBarOverlaysWebView defaults to true not work {broken}

### ISSUE THREAD

**Issue by mosabab** [apache/cordova-plugin-statusbar#170] opened 2019-11-08 16:57 UTC
# Bug Report

### What is expected to happen?

The statusbar  should overlay the webview.

* According to the plugin docs: 
the preference StatusBarOverlaysWebView (boolean, defaults to true).

### What does actually happen?
The status bar became in solid blank, and not overlay the webview.

- the preference StatusBarOverlaysWebView defaults to true not working.

## Information

![Untitled-1](https://user-images.githubusercontent.com/47486787/68495433-d7da3180-0258-11ea-858e-84b66ab46bb9.jpg)

Maybe someone know how this issue can be solved !

### Environment, Platform, Device

- Any new android devices.

### Version information

- Phonegap/Cordova CLI 9.0.0 (Android 8.0.0)
- cordova-plugin-statusbar master version.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by mosababubakr** [comment] 2019-11-08 17:05
@breautek  sorry for the ping, but could you please take a look into this if you have any idea?
Regards

**Comment by breautek** [comment] 2019-11-08 20:40
You may be hitting the bug as reported at https://github.com/apache/cordova-plugin-statusbar/issues/151 where android doesn't actually read the `StatusBarOverlaysWebView` preference. There is a pending PR to fix that, but with requested changes, and the author of the PR hasn't responded in quite awhile.

**Comment by mosababubakr** [comment] 2019-11-08 20:58
> You may be hitting the bug as reported at #151 where android doesn't actually read the `StatusBarOverlaysWebView` preference. There is a pending PR to fix that, but with requested changes, and the author of the PR hasn't responded in quite awhile.
> 
> Workaround described at [#151 (comment)](https://github.com/apache/cordova-plugin-statusbar/issues/151#issuecomment-527485644)

Thanks for reply,

Does this issue is the same old issue for ios before we add  view-fit=cover to support ios ?

**Comment by mosababubakr** [comment] 2019-11-08 21:05
Why the pending PR still in request because who made the PR still not respond, I think anyone who is familiar with these codes can make a new PR and then done by approved, because this is high priority bug that need to be solved.

**Comment by breautek** [comment] 2019-11-09 01:06
> Does this issue is the same old issue for ios before we add view-fit=cover to support ios ?

Not sure what old issue you are referring to, but the issue I linked is an android issue only. iOS has always read the preference. I believe the source of the problem is the feature was implemented for iOS only originally.

> Why the pending PR still in request because who made the PR still not respond

Because Cordova is 100% volunteer based and many of us is very busy.

>  I think anyone who is familiar with these codes can make a new PR and then done by approved

I agree, and honestly the changes required to fix #151 issue is rather trivial, PRs welcome, even if there is already a pending one.

But to confirm that this is even the problem that you are facing, I would use the JS API to set statusbar overlay to enable the statusbar. If that makes the statusbar work as expected, then we can confidently say that you were hitting the same issue as #151.

**Comment by mosababubakr** [comment] 2019-11-09 09:37
You are true.
I try yo use JS API and i will tell you if it work or not.

Regards

**Comment by mosababubakr** [comment] 2019-11-10 20:03
Hello @breautek 
I add js api and work, but i think this just temporary solution and not the optimal.
Maybe someone can solve this issue soon.
Regards

**Comment by breautek** [comment] 2019-11-10 20:36
Yes, this was just a confirmation that you weren't experiencing a different problem than #151

**Comment by diamond95** [comment] 2019-11-18 09:09
> Hello @breautek
> I add js api and it work, but i think this just temporary solution and not the optimal.
> Maybe someone can solve this issue soon.
> Regards

Can you show me example how it works for you?

**Comment by mosababubakr** [comment] 2019-11-18 10:12
Hello @diamond95 

You can add `StatusBar.overlaysWebView(true);` after deviceReady Event fires.

for e.g.: 

function onDeviceReady() {
    StatusBar.overlaysWebView(true);

    // other codes........
}

**Comment by mosababubakr** [comment] 2019-11-18 10:15
Hello @diamond95 

You can add `StatusBar.overlaysWebView(true);` after deviceReady Event fires.

for e.g.:


document.addEventListener("deviceready", onDeviceReady, false);

function onDeviceReady() {


   if (cordova.platformId == 'android') {
    StatusBar.overlaysWebView(true);
}


   //......... some codes........
}

**Comment by mosababubakr** [comment] 2019-11-18 10:15
> > Hello @breautek
> > I add js api and it work, but i think this just temporary solution and not the optimal.
> > Maybe someone can solve this issue soon.
> > Regards
> 
> Can you show me example how it works for you?

Hello @diamond95 

You can add `StatusBar.overlaysWebView(true);` after deviceReady Event fires.

for e.g.:


document.addEventListener("deviceready", onDeviceReady, false);

function onDeviceReady() {


   if (cordova.platformId == 'android') {
    StatusBar.overlaysWebView(true);
}


   //......... some codes........
}

**Comment by diamond95** [comment] 2019-11-18 10:18
@mosababubakr well, it does not work for me when I compile mobile application on android 9

**Comment by mosababubakr** [comment] 2019-11-18 10:22
> @mosababubakr well, it does not work for me when I compile mobile application on android 9

do you try to put the following code and not work ?

function onDeviceReady() {

StatusBar.overlaysWebView(true);

//......... other codes........
}

**Comment by diamond95** [comment] 2019-11-18 10:36
@mosababubakr I did already open bug, https://github.com/apache/cordova-plugin-statusbar/issues/155

**Comment by mosababubakr** [comment] 2019-11-18 10:44
@diamond95 

did you used the master version of the plugin ?
do you used the latest cli for phonegap/ cordova ?

**Comment by diamond95** [comment] 2019-11-18 11:09
@mosababubakr Yup. Can you push to github some example with working status bar ? I would like to check that.. 

Thanks anyway

**Comment by mosababubakr** [comment] 2019-11-18 12:04
@diamond95 I just put `<preference name="StatusBarOverlaysWebView" value="true" />` in the `config.xml` file. 
And put the following code in `onDeviceReady()` function like this:

function onDeviceReady() {

StatusBar.overlaysWebView(true);

}

**Comment by breautek** [comment] 2019-11-18 13:30
`StatusBar.overlaysWebView(true);` may not consistently work properly when called from the `deviceready`. There is some sort of race condition. I don't see it on my production apps, but on simple apps I do see the issue. That issue is being tracked at https://github.com/apache/cordova-plugin-statusbar/issues/158

Currently `<preference name="StatusBarOverlaysWebView" value="true" />` does nothing for android, as android doesn't read the preference value. The PR https://github.com/apache/cordova-plugin-statusbar/pull/171 will address this issue, but is only expected to land in master when prepping for the next major release.

So far the best way to avoid #158 is to apply #171 PR to your own fork so that you can use the `StatusBarOverlaysWebView` preference. In my testing, the status bar appears to consistently work as expected when the overlay is being applied in the plugin initialisation.

**Comment by mosabab** [comment] 2019-11-18 13:45
> `StatusBar.overlaysWebView(true);` may not consistently work properly when called from the `deviceready`. There is some sort of race condition. I don't see it on my production apps, but on simple apps I do see the issue. That issue is being tracked at #158
> 
> Currently `<preference name="StatusBarOverlaysWebView" value="true" />` does nothing for android, as android doesn't read the preference value. The PR #171 will address this issue, but is only expected to land in master when prepping for the next major release.
> 
> So far the best way to avoid #158 is to apply #171 PR to your own fork so that you can use the `StatusBarOverlaysWebView` preference. In my testing, the status bar appears to consistently work as expected when the overlay is being applied in the plugin initialisation.

when the PR will be merged and done if it ready ?

**Comment by breautek** [comment] 2019-11-18 13:55
> when the PR will be merged and done if it ready ?

#171 is a breaking change, even though it's fixing a bug because it's changing the default behaviour of the android platform, so the PR will only be merged once preparations for the next major starts. I can't really give a timeline when that will happen, but there are a few other PRs also waiting for a major version bump.

**Comment by WuglyakBolgoink** [comment] 2020-03-04 11:49
03.2020 nothing happen... Ping?!

**Comment by maswerdna** [comment] 2020-04-09 09:49
What's the update on this? Is anyone still working on something?

**Closed** 2020-04-12 00:12 UTC
