### ISSUE TITLE
Plugin breaks with WKWebView Engine

### ISSUE THREAD

**Issue by barrenc0de** [apache/cordova-plugin-statusbar#175] opened 2019-12-28 08:59 UTC
As lon as I'm using the standard WebView, the Overlay=true/false switch and background colour works perfectly. But when I add the WKWebview Engine Plugin to my Cordova project, it seems to ignore the status bar plugin entirely.

### What is expected to happen?

should apply overlay true/false and background-colour

### What does actually happen?

ignores these settings completely, as if plugin isn't even installed

### Version information
Cordova ios 5.1.1
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine"
phonegap-plugin-speech-synthesis 0.1.1 "SpeechSynthesis"

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by kerrydp** [comment] 2020-01-30 08:04
Also experiencing this.  The viewport is leaving a statusbar-height-sized gap at the bottom of the screen.  When I scroll content, it doesn't scroll within this bottom gap.

If I uninstall cordova-plugin-wkwebview-engine, then this bottom gap is removed and the viewport extends all the way to the bottom of the screen, as expected.

<img width="559" alt="Screen Shot 2020-01-30 at 2 55 46 PM" src="https://user-images.githubusercontent.com/48201281/73430903-01ac7b80-43a4-11ea-867f-63b65dd70042.png">

**Comment by jacobg** [comment] 2020-02-11 20:10
I'm having the same exact problem. See screenshot below.

It seems that the status bar elements are white, even though the cordova preference is set to `lightcontent`, i.e., elements should be dark. I tried other styles too, but it doesn't make a difference. And in Safari Inspector, `window.StatusBar `does nothing to change anything.

Is anyone looking at this issue, or is there a resolution?

<img width="410" alt="Screen Shot 2020-02-11 at 3 08 53 PM" src="https://user-images.githubusercontent.com/736985/74274662-722a9500-4ce0-11ea-9866-9ebd202e8a01.png">

**Comment by brodybits** [comment] 2020-02-11 20:14
I have never personally worked on this plugin and other maintainers seem to be a bit overloaded. I would highly recommend you consider reaching out on Slack or on the mailing list, follow the links in the footer of cordova.io or cordova.apache.org.

**Comment by jacobg** [comment] 2020-02-11 21:21
I figured out it's caused by Dark Mode on iOS 13. If I turn Dark Mode off, then the status bar looks fine. Explicitly setting status bar style in Dark Mode doesn't do anything. I have to investigate that further. It's weird, because in my older app version on iOS 13, using UIWebView (which may or may not be related), it does not have this issue. I suppose it might be because my app was using an older version of the iOS SDK before Dark Mode came out; and now that it's using the current SDK then Dark Mode gets enabled even though my app is not yet themed for that.

**Comment by gabrielenosso** [comment] 2020-02-18 00:24
Any news there?

I tried to specify the key UIUserInterfaceStyle  as "light", but it doesn't work...

**Comment by matheustavaresdev** [comment] 2020-03-04 08:17
Please take a look at this https://github.com/apache/cordova-plugin-statusbar/issues/148#issuecomment-594383943

Working workaround.

**Comment by bcolflesh** [comment] 2020-03-12 21:05
Also experiencing this.

cordova-lib@9.0.1

Requirements check results for ios:
Apple macOS: installed darwin
Xcode: installed 11.3.1
ios-deploy: installed 1.10.0
CocoaPods: installed 1.9.0

**Comment by bcolflesh** [comment] 2020-03-20 17:42
Anyone successfully set preferences on iOS 13.x with WKWebView yet?

`<preference name="StatusBarBackgroundColor" value="#000000" />
<preference name="StatusBarStyle" value="blackopaque" />`

**Comment by BradCB** [comment] 2020-04-03 14:39
Also experiencing this.

The status text is hidden but this grey bar is showing.
It's happening in iPhone 6,7,8,9,10,11 simulators and iPhone 6 device.

 It wasn't showing when I was using UIWebView but now that WKWebView is required we have to use it for iOS. 

![Capture](https://user-images.githubusercontent.com/8985796/78372115-1a910300-7586-11ea-9cdf-4cca183251bd.PNG)

**Comment by fgarcia5** [comment] 2020-04-04 12:34
> gap at the bottom

I have found the following workaround for this issue
https://stackoverflow.com/a/49122361/4208571
This worked for me

**Comment by knubie** [comment] 2020-04-06 19:57
In my case none of the `config.xml` preferences do anything, and the `StatusBar` js object is undefined.

I know that the plugin is loaded because all of the default options are in effect (`StatusBarOverlaysWebView` is on, and `StatusBarStyle` is set to `lightcontent`).

This is all on iOS 13.

**Comment by jcesarmobile** [comment] 2020-04-11 23:29
There are at least 3 different issues here, probably because the original reported one is not very clear.
For the statusbar text being always white, the problem is iOS 13 sets the "default" color based on the device mode. That's already fixed in master, default will always be black https://github.com/apache/cordova-plugin-statusbar/pull/169. 
There is another PR to make default have the default behavior and instead use a new darkContent https://github.com/apache/cordova-plugin-statusbar/pull/181, so if you want that behavior, comment on https://github.com/apache/cordova-plugin-statusbar/issues/164, because last time I asked people wanted default to be black and not change based on the device mode.
For the gap on the bottom, thats a WKWebView "feature", to fix it you have to use viewport-fit cover and 100vh as height instead of 100%. see https://github.com/apache/cordova-plugin-wkwebview-engine/pull/107
other one was a InAppBrowser bug. 
The original bug is "not working on WKWebView", and I can't reproduce that, so I'm closing the issue.

**Closed by jcesarmobile** 2020-04-11 23:29 UTC

**Comment by davigasperin** [comment] 2020-05-05 02:37
Hello, any solution for this?

**Comment by barrenc0de** [comment] 2020-05-05 07:35
I eventually solved this by uninstalling the WKWebView engine and using [cordova-plugin-ionic-webview](https://github.com/ionic-team/cordova-plugin-ionic-webview) instead.
