### ISSUE TITLE
statusbar overlaysWebView defaults to true not work on android

### ISSUE THREAD

**Issue by huiofe** [apache/cordova-plugin-statusbar#174] opened 2019-11-18 01:57 UTC
# Bug Report

## Problem
onDeviceReady I set overlaysWebview to true, but it's not work. But it worked again when system keyboard show. That is very strange!!  I used this plugin on android 8.0
## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment] 2019-11-18 02:28
duplicate of https://github.com/apache/cordova-plugin-statusbar/issues/158

**Closed by breautek** 2019-11-18 02:28 UTC
